[
    { "english": "time", "portuguese": "tempo" },
    { "english": "long", "portuguese": "extenso" },
    { "english": "little", "portuguese": "pouco" },
    { "english": "good", "portuguese": "bom" },
    { "english": "new", "portuguese": "novo" },
    { "english": "same", "portuguese": "mesmo" },
    { "english": "right", "portuguese": "direito" },
    { "english": "different", "portuguese": "diferente" },
    { "english": "old", "portuguese": "velho" },
    { "english": "small", "portuguese": "pequeno" },
    { "english": "big", "portuguese": "grande" },
    { "english": "own", "portuguese": "próprio" },
    { "english": "last", "portuguese": "passado" },
    { "english": "left", "portuguese": "esquerda" },
    { "english": "large", "portuguese": "grande" },
    { "english": "important", "portuguese": "importante" },
    { "english": "enough", "portuguese": "suficiente" },
    { "english": "second", "portuguese": "segunda" },
    { "english": "first", "portuguese": "primeiro" },
    { "english": "well", "portuguese": "bem" },
    { "english": "next", "portuguese": "próximo" },
    { "english": "live", "portuguese": "ao vivo" },
    { "english": "high", "portuguese": "alta" },
    { "english": "following", "portuguese": "seguinte" },
    { "english": "used", "portuguese": "usado" },
    { "english": "even", "portuguese": "igual" },
    { "english": "is", "portuguese": "é" },
    { "english": "was", "portuguese": "foi" },
    { "english": "are", "portuguese": "são" },
    { "english": "be", "portuguese": "ser" },
    { "english": "have", "portuguese": "ter" },
    { "english": "had", "portuguese": "tinha" },
    { "english": "were", "portuguese": "foram" },
    { "english": "can", "portuguese": "pode" },
    { "english": "said", "portuguese": "disse" },
    { "english": "do", "portuguese": "fazer" },
    { "english": "will", "portuguese": "vai" },
    { "english": "would", "portuguese": "iria" },
    { "english": "has", "portuguese": "tem" },
    { "english": "could", "portuguese": "poderia" },
    { "english": "make", "portuguese": "fazer" },
    { "english": "been", "portuguese": "foi" },
    { "english": "did", "portuguese": "fez" },
    { "english": "find", "portuguese": "encontrar" },
    { "english": "use", "portuguese": "usar" },
    { "english": "know", "portuguese": "saber" },
    { "english": "get", "portuguese": "obter" },
    { "english": "go", "portuguese": "ir" },
    { "english": "write", "portuguese": "escrever" },
    { "english": "look", "portuguese": "olhar" },
    { "english": "think", "portuguese": "pensar" },
    { "english": "came", "portuguese": "veio" },
    { "english": "come", "portuguese": "vir" },
    { "english": "must", "portuguese": "deve" },
    { "english": "does", "portuguese": "faz" },
    { "english": "should", "portuguese": "deveria" },
    { "english": "see", "portuguese": "ver" },
    { "english": "take", "portuguese": "tomar" },
    { "english": "hear", "portuguese": "ouvir" },
    { "english": "feel", "portuguese": "sentir" },
    { "english": "go", "portuguese": "ir" },
    { "english": "say", "portuguese": "dizer" },
    { "english": "like", "portuguese": "gostar" },
    { "english": "talk", "portuguese": "conversar" },
    { "english": "work", "portuguese": "trabalhar" },
    { "english": "give", "portuguese": "dar" },
    { "english": "find", "portuguese": "encontrar" },
    { "english": "help", "portuguese": "ajudar" },
    { "english": "try", "portuguese": "tentar" },
    { "english": "show", "portuguese": "mostrar" },
    {"english": "time", "portuguese": "tempo"},
    {"english": "people", "portuguese": "pessoas"},
    {"english": "way", "portuguese": "modo"},
    {"english": "water", "portuguese": "água"},
    {"english": "words", "portuguese": "palavras"},
    {"english": "man", "portuguese": "homem"},
    {"english": "work", "portuguese": "trabalho"},
    {"english": "word", "portuguese": "palavra"},
    {"english": "part", "portuguese": "parte"},
    {"english": "place", "portuguese": "lugar"},
    {"english": "things", "portuguese": "coisas"},
    {"english": "years", "portuguese": "anos"},
    {"english": "number", "portuguese": "número"},
    {"english": "men", "portuguese": "homens"},
    {"english": "name", "portuguese": "nome"},
    {"english": "mister", "portuguese": "senhor"},
    {"english": "home", "portuguese": "casa"},
{"english": "air", "portuguese": "ar"},
{"english": "line", "portuguese": "linha, fila"},
{"english": "end", "portuguese": "final"},
{"english": "sound", "portuguese": "som"},
{"english": "house", "portuguese": "casa"},
{"english": "world", "portuguese": "mundo"},
{"english": "school", "portuguese": "escola"},
{"english": "form", "portuguese": "forma"},
{"english": "food", "portuguese": "comida"},
{"english": "children", "portuguese": "crianças"},
{"english": "feet", "portuguese": "pés"},
{"english": "land", "portuguese": "terra"},
{"english": "side", "portuguese": "lado"},
{"english": "boy", "portuguese": "menino"},
{"english": "animals", "portuguese": "animais"},
{"english": "life", "portuguese": "vida"},
{"english": "head", "portuguese": "cabeça"},
{"english": "kind", "portuguese": "tipo"},
{"english": "page", "portuguese": "página"},
{"english": "earth", "portuguese": "terra"},
{"english": "hand", "portuguese": "mão"},
{"english": "year", "portuguese": "ano"},
{"english": "mother", "portuguese": "mãe"},
{"english": "light", "portuguese": "luz"},
{"english": "parts", "portuguese": "partes, peças"},
{"english": "country", "portuguese": "país"},
{"english": "father", "portuguese": "pai"},
{"english": "picture", "portuguese": "imagem"},
{"english": "eyes", "portuguese": "olhos"},
{"english": "times", "portuguese": "vezes"},
{"english": "help", "portuguese": "ajuda"},
{"english": "thought", "portuguese": "pensamento"},
{"english": "show", "portuguese": "show"},
{"english": "night", "portuguese": "noite"},
{"english": "story", "portuguese": "história"},
{"english": "boys", "portuguese": "meninos"},
{"english": "long", "portuguese": "extenso"},
{"english": "little", "portuguese": "pouco"},
{"english": "good", "portuguese": "bom"},
{"english": "new", "portuguese": "novo"},
{"english": "same", "portuguese": "mesmo"},
{"english": "right", "portuguese": "direito"},
{"english": "different", "portuguese": "diferente"},
{"english": "old", "portuguese": "velho, antigo"},
{"english": "great", "portuguese": "grande, ótimo"},
{"english": "small", "portuguese": "pequeno"},
{"english": "big", "portuguese": "grande"},
{"english": "own", "portuguese": "próprio"},
{"english": "last", "portuguese": "passado"},
{"english": "left", "portuguese": "esquerda"},
{"english": "large", "portuguese": "grande"},
{"english": "important", "portuguese": "importante"},
{"english": "enough", "portuguese": "suficiente"},
{"english": "second", "portuguese": "segunda"},
{"english": "first", "portuguese": "primeiro"},
{"english": "well", "portuguese": "bem"},
{"english": "next", "portuguese": "próximo"},
{"english": "live", "portuguese": "ao vivo"},
{"english": "high", "portuguese": "alta"},
{"english": "following", "portuguese": "seguinte"},
{"english": "used", "portuguese": "usado"},
{"english": "even", "portuguese": "igual"},
{"english": "is", "portuguese": "é"},
{"english": "was", "portuguese": "foi"},
{"english": "are", "portuguese": "são"},
{"english": "be", "portuguese": "ser"},
{"english": "have", "portuguese": "ter"},
{"english": "had", "portuguese": "tinha"},
{"english": "were", "portuguese": "foram"},
{"english": "can", "portuguese": "pode"},
{"english": "said", "portuguese": "disse"},
{"english": "do", "portuguese": "fazer"},
{"english": "will", "portuguese": "vai"},
{"english": "would", "portuguese": "iria"},
{"english": "has", "portuguese": "tem"},
{"english": "could", "portuguese": "poderia"},
{"english": "make", "portuguese": "fazer"},
{"english": "been", "portuguese": "foi"},
{"english": "did", "portuguese": "fez"},
{"english": "find", "portuguese": "encontrar"},
{"english": "use", "portuguese": "usar"},
{"english": "know", "portuguese": "saber"},
{"english": "get", "portuguese": "obter"},
{"english": "go", "portuguese": "ir"},
{"english": "write", "portuguese": "escrever"},
{"english": "look", "portuguese": "olhar"},
{"english": "think", "portuguese": "pensar"},
{"english": "came", "portuguese": "veio"},
{"english": "come", "portuguese": "vir"},
{"english": "must", "portuguese": "deve"},
{"english": "does", "portuguese": "faz"},
{"english": "put", "portuguese": "colocar"},
{"english": "went", "portuguese": "foi"},
{"english": "tell", "portuguese": "dizer"},
{"english": "say", "portuguese": "dizer"},
{"english": "should", "portuguese": "deveria"},
{"english": "give", "portuguese": "dar"},
{"english": "read", "portuguese": "ler"},
{"english": "might", "portuguese": "poderia"},
{"english": "saw", "portuguese": "viu"},
{"english": "asked", "portuguese": "perguntou"},
{"english": "don’t", "portuguese": "não faça"},
{"english": "going", "portuguese": "vai"},
{"english": "want", "portuguese": "querer"},
{"english": "keep", "portuguese": "manter"},
{"english": "took", "portuguese": "levou"},
{"english": "began", "portuguese": "começou"},
{"english": "got", "portuguese": "obteve"},
{"english": "need", "portuguese": "necessitar"},
{"english": "let", "portuguese": "deixar"},
{"english": "being", "portuguese": "sendo"},
{"english": "see", "portuguese": "ver"},
{"english": "made", "portuguese": "feito"},
{"english": "may", "portuguese": "pode"},
{"english": "take", "portuguese": "pegar"},
{"english": "found", "portuguese": "encontrado"},
{"english": "set", "portuguese": "estabelecer"},
{"english": "looked", "portuguese": "olhou"},
{"english": "study", "portuguese": "estudar"},
{"english": "called", "portuguese": "chamou"},
{"english": "you", "portuguese": "você"},
{"english": "it", "portuguese": "ele, ela"},
{"english": "he", "portuguese": "ele"},
{"english": "they", "portuguese": "eles"},
{"english": "this", "portuguese": "isto"},
{"english": "I", "portuguese": "eu"},
{"english": "what", "portuguese": "o que"},
{"english": "all", "portuguese": "todos"},
{"english": "we", "portuguese": "nós"},
{"english": "which", "portuguese": "que"},
{"english": "each", "portuguese": "cada"},
{"english": "them", "portuguese": "eles"},
{"english": "she", "portuguese": "ela"},
{"english": "some", "portuguese": "alguns"},
{"english": "these", "portuguese": "esses"},
{"english": "who", "portuguese": "quem"},
{"english": "me", "portuguese": "me, mim"},
{"english": "another", "portuguese": "outro"},
{"english": "us", "portuguese": "nos"},
{"english": "something", "portuguese": "algo"},
{"english": "both", "portuguese": "ambos"},
{"english": "those", "portuguese": "aqueles"},
{"english": "the", "portuguese": "o, a, os, as"},
{"english": "a", "portuguese": "um"},
{"english": "that", "portuguese": "aquele, isso, aquilo, que"},
{"english": "his", "portuguese": "dele"},
{"english": "this", "portuguese": "este, isto"},
{"english": "an", "portuguese": "um"},
{"english": "your", "portuguese": "seu, sua"},
{"english": "their", "portuguese": "deles, delas"},
{"english": "other", "portuguese": "outros"},
{"english": "more", "portuguese": "mais"},
{"english": "him", "portuguese": "ele"},
{"english": "its", "portuguese": "dele, dela"},
{"english": "my", "portuguese": "meu, minha"},
{"english": "much", "portuguese": "muito"},
{"english": "our", "portuguese": "nosso, nossa"},
{"english": "any", "portuguese": "qualquer"},
{"english": "such", "portuguese": "tanto, tal"},
{"english": "every", "portuguese": "cada"},
{"english": "many", "portuguese": "muitos"},
{"english": "as", "portuguese": "como"},
{"english": "of", "portuguese": "de"},
{"english": "to", "portuguese": "para"},
{"english": "in", "portuguese": "em"},
{"english": "for", "portuguese": "para"},
{"english": "on", "portuguese": "em"},
{"english": "with", "portuguese": "com"},
{"english": "at", "portuguese": "em"},
{"english": "from", "portuguese": "de"},
{"english": "by", "portuguese": "por"},
{"english": "about", "portuguese": "sobre"},
{"english": "into", "portuguese": "em"},
{"english": "like", "portuguese": "como"},
{"english": "after", "portuguese": "depois"},
{"english": "through", "portuguese": "através"},
{"english": "before", "portuguese": "antes"},
{"english": "under", "portuguese": "debaixo"},
{"english": "along", "portuguese": "junto"},
{"english": "until", "portuguese": "até"},
{"english": "without", "portuguese": "sem"},
{"english": "between", "portuguese": "entre"},
{"english": "and", "portuguese": "e"},
{"english": "or", "portuguese": "ou"},
{"english": "but", "portuguese": "mas"},
{"english": "if", "portuguese": "se"},
{"english": "than", "portuguese": "que"},
{"english": "because", "portuguese": "porque"},
{"english": "while", "portuguese": "enquanto"},
{"english": "when", "portuguese": "quando"},
{"english": "how", "portuguese": "como"},
{"english": "up", "portuguese": "para cima"},
{"english": "out", "portuguese": "fora"},
{"english": "then", "portuguese": "então, depois"},
{"english": "so", "portuguese": "tão, então"},
{"english": "no", "portuguese": "não"},
{"english": "not", "portuguese": "não"},
{"english": "now", "portuguese": "agora"},
{"english": "over", "portuguese": "superior, mais"},
{"english": "down", "portuguese": "baixo"},
{"english": "only", "portuguese": "apenas"},
{"english": "very", "portuguese": "muito"},
{"english": "just", "portuguese": "apenas"},
{"english": "where", "portuguese": "onde"},
{"english": "most", "portuguese": "mais"},
{"english": "too", "portuguese": "também"},
{"english": "also", "portuguese": "também"},
{"english": "around", "portuguese": "em torno de"},
{"english": "here", "portuguese": "aqui"},
{"english": "why", "portuguese": "por que"},
{"english": "away", "portuguese": "distância"},
{"english": "again", "portuguese": "novamente"},
{"english": "off", "portuguese": "fora"},
{"english": "still", "portuguese": "ainda"},
{"english": "never", "portuguese": "nunca"},
{"english": "below", "portuguese": "abaixo"},
{"english": "always", "portuguese": "sempre"},
{"english": "often", "portuguese": "muitas vezes"},
{"english": "together", "portuguese": "juntos"},
{"english": "once", "portuguese": "uma vez"},
{"english": "sometimes", "portuguese": "às vezes"},
{"english": "above", "portuguese": "acima"},
{"english": "almost", "portuguese": "quase"},
{"english": "far", "portuguese": "longe"},
{"english": "back", "portuguese": "de volta"},
{"english": "one", "portuguese": "um"},
{"english": "two", "portuguese": "dois"},
{"english": "three", "portuguese": "três"},
{"english": "few", "portuguese": "poucos"},
{"english": "four", "portuguese": "quatro"}

    
]
